server:
  port: 9091

spring:
  application:
    name: statistics
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/USERSERVICE_NEW?autoreconnect=true?useUnicode=yes&characterEncoding=UTF-8"
    password: "root"
    username: "root"
